Update typing imports to use Dict instead of dict
File "/usr/local/lib/python3.8/site-packages/weasel/util/__init__.py", line 13, in <module>
from .remote import download_file, upload_file
File "/usr/local/lib/python3.8/site-packages/weasel/util/remote.py", line 62, in <module>
def _transport_params(url: str) -> Optional[dict[str, Any]]:
TypeError: 'type' object is not subscriptable